import re
def clean_d(d):
    d = d.lower()
    d = re.sub(r"[-()\"#/@;:<>{}`+=~|.!?,]", "", d)
    d = re.sub(r"i'm", "i am", d)
    d = re.sub(r"\'d", " would", d)
    d = re.sub(r"how's", "how is", d)
    d = re.sub(r"what's up?", "what is hapenning", d)
    d = re.sub(r"it's", "it is", d)
    d = re.sub(r"n'", "ng", d)
    d = re.sub(r"n't", " not", d)
    d = re.sub(r"he's", "he is", d)
    d = re.sub(r"she's", "she is", d)
    d = re.sub(r"that's", "that is", d)
    d = re.sub(r"\'ve", " have", d)
    d = re.sub(r"\'ll", " will", d)
    d = re.sub(r"'bout", "about", d)
    d = re.sub(r"\'re", " are", d)
    d = re.sub(r"\'re", " are", d)
    d = re.sub(r"won't", "will not", d)
    d = re.sub(r"can't", "cannot", d)
    d = re.sub(r"'til", "until", d)
    d = re.sub(r"where's", "where is", d)
    return d